//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VZF.Types.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yaf_Attachment
    {
        public int AttachmentID { get; set; }
        public int MessageID { get; set; }
        public string FileName { get; set; }
        public int Bytes { get; set; }
        public Nullable<int> FileID { get; set; }
        public string ContentType { get; set; }
        public int Downloads { get; set; }
        public byte[] FileData { get; set; }
    
        public virtual yaf_Message yaf_Message { get; set; }
    }
}
