//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VZF.Types.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yaf_EventLog
    {
        public int EventLogID { get; set; }
        public System.DateTime EventTime { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Source { get; set; }
        public string Description { get; set; }
        public int Type { get; set; }
    
        public virtual yaf_User yaf_User { get; set; }
    }
}
