//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VZF.Types.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yaf_Extension
    {
        public int ExtensionID { get; set; }
        public int BoardId { get; set; }
        public string Extension { get; set; }
    
        public virtual yaf_Board yaf_Board { get; set; }
    }
}
