//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VZF.Types.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yaf_Group
    {
        public yaf_Group()
        {
            this.yaf_EventLogGroupAccess = new HashSet<yaf_EventLogGroupAccess>();
            this.yaf_ForumAccess = new HashSet<yaf_ForumAccess>();
            this.yaf_GroupMedal = new HashSet<yaf_GroupMedal>();
            this.yaf_User = new HashSet<yaf_User>();
        }
    
        public int GroupID { get; set; }
        public int BoardID { get; set; }
        public string Name { get; set; }
        public int Flags { get; set; }
        public int PMLimit { get; set; }
        public string Style { get; set; }
        public short SortOrder { get; set; }
        public string Description { get; set; }
        public int UsrSigChars { get; set; }
        public string UsrSigBBCodes { get; set; }
        public string UsrSigHTMLTags { get; set; }
        public int UsrAlbums { get; set; }
        public int UsrAlbumImages { get; set; }
        public Nullable<bool> IsHidden { get; set; }
        public Nullable<bool> IsUserGroup { get; set; }
    
        public virtual yaf_Board yaf_Board { get; set; }
        public virtual ICollection<yaf_EventLogGroupAccess> yaf_EventLogGroupAccess { get; set; }
        public virtual ICollection<yaf_ForumAccess> yaf_ForumAccess { get; set; }
        public virtual ICollection<yaf_GroupMedal> yaf_GroupMedal { get; set; }
        public virtual ICollection<yaf_User> yaf_User { get; set; }
    }
}
