//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VZF.Types.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yaf_MessageReported
    {
        public yaf_MessageReported()
        {
            this.yaf_MessageReportedAudit = new HashSet<yaf_MessageReportedAudit>();
        }
    
        public int MessageID { get; set; }
        public string Message { get; set; }
        public Nullable<bool> Resolved { get; set; }
        public Nullable<int> ResolvedBy { get; set; }
        public Nullable<System.DateTime> ResolvedDate { get; set; }
    
        public virtual ICollection<yaf_MessageReportedAudit> yaf_MessageReportedAudit { get; set; }
    }
}
