//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VZF.Types.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yaf_Topic
    {
        public yaf_Topic()
        {
            this.yaf_Active = new HashSet<yaf_Active>();
            this.yaf_FavoriteTopic = new HashSet<yaf_FavoriteTopic>();
            this.yaf_Forum = new HashSet<yaf_Forum>();
            this.yaf_Message = new HashSet<yaf_Message>();
            this.yaf_NntpTopic = new HashSet<yaf_NntpTopic>();
            this.yaf_Topic1 = new HashSet<yaf_Topic>();
            this.yaf_TopicReadTracking = new HashSet<yaf_TopicReadTracking>();
            this.yaf_WatchTopic = new HashSet<yaf_WatchTopic>();
        }
    
        public int TopicID { get; set; }
        public int ForumID { get; set; }
        public int UserID { get; set; }
        public string UserName { get; set; }
        public System.DateTime Posted { get; set; }
        public string Topic { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public int Views { get; set; }
        public short Priority { get; set; }
        public Nullable<int> PollID { get; set; }
        public Nullable<int> TopicMovedID { get; set; }
        public Nullable<System.DateTime> LastPosted { get; set; }
        public Nullable<int> LastMessageID { get; set; }
        public Nullable<int> LastUserID { get; set; }
        public string LastUserName { get; set; }
        public int NumPosts { get; set; }
        public int Flags { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsQuestion { get; set; }
        public Nullable<int> AnswerMessageId { get; set; }
        public Nullable<int> LastMessageFlags { get; set; }
        public string TopicImage { get; set; }
        public string Styles { get; set; }
        public Nullable<System.DateTime> LinkDate { get; set; }
        public string UserDisplayName { get; set; }
        public string LastUserDisplayName { get; set; }
    
        public virtual ICollection<yaf_Active> yaf_Active { get; set; }
        public virtual ICollection<yaf_FavoriteTopic> yaf_FavoriteTopic { get; set; }
        public virtual ICollection<yaf_Forum> yaf_Forum { get; set; }
        public virtual yaf_Forum yaf_Forum1 { get; set; }
        public virtual ICollection<yaf_Message> yaf_Message { get; set; }
        public virtual yaf_Message yaf_Message1 { get; set; }
        public virtual ICollection<yaf_NntpTopic> yaf_NntpTopic { get; set; }
        public virtual yaf_PollGroupCluster yaf_PollGroupCluster { get; set; }
        public virtual ICollection<yaf_Topic> yaf_Topic1 { get; set; }
        public virtual yaf_Topic yaf_Topic2 { get; set; }
        public virtual yaf_User yaf_User { get; set; }
        public virtual yaf_User yaf_User1 { get; set; }
        public virtual ICollection<yaf_TopicReadTracking> yaf_TopicReadTracking { get; set; }
        public virtual ICollection<yaf_WatchTopic> yaf_WatchTopic { get; set; }
    }
}
