//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VZF.Types.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yaf_User
    {
        public yaf_User()
        {
            this.yaf_Active = new HashSet<yaf_Active>();
            this.yaf_AdminPageUserAccess = new HashSet<yaf_AdminPageUserAccess>();
            this.yaf_Buddy = new HashSet<yaf_Buddy>();
            this.yaf_CheckEmail = new HashSet<yaf_CheckEmail>();
            this.yaf_EventLog = new HashSet<yaf_EventLog>();
            this.yaf_FavoriteTopic = new HashSet<yaf_FavoriteTopic>();
            this.yaf_Forum = new HashSet<yaf_Forum>();
            this.yaf_ForumReadTracking = new HashSet<yaf_ForumReadTracking>();
            this.yaf_Message = new HashSet<yaf_Message>();
            this.yaf_PMessage = new HashSet<yaf_PMessage>();
            this.yaf_ReputationVote = new HashSet<yaf_ReputationVote>();
            this.yaf_ReputationVote1 = new HashSet<yaf_ReputationVote>();
            this.yaf_Thanks = new HashSet<yaf_Thanks>();
            this.yaf_Topic = new HashSet<yaf_Topic>();
            this.yaf_Topic1 = new HashSet<yaf_Topic>();
            this.yaf_TopicReadTracking = new HashSet<yaf_TopicReadTracking>();
            this.yaf_UserForum = new HashSet<yaf_UserForum>();
            this.yaf_UserMedal = new HashSet<yaf_UserMedal>();
            this.yaf_UserPMessage = new HashSet<yaf_UserPMessage>();
            this.yaf_UserProfile = new HashSet<yaf_UserProfile>();
            this.yaf_WatchForum = new HashSet<yaf_WatchForum>();
            this.yaf_WatchTopic = new HashSet<yaf_WatchTopic>();
            this.yaf_Group = new HashSet<yaf_Group>();
        }
    
        public int UserID { get; set; }
        public int BoardID { get; set; }
        public string ProviderUserKey { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public System.DateTime Joined { get; set; }
        public System.DateTime LastVisit { get; set; }
        public string IP { get; set; }
        public int NumPosts { get; set; }
        public int TimeZone { get; set; }
        public string Avatar { get; set; }
        public string Signature { get; set; }
        public byte[] AvatarImage { get; set; }
        public string AvatarImageType { get; set; }
        public int RankID { get; set; }
        public Nullable<System.DateTime> Suspended { get; set; }
        public string LanguageFile { get; set; }
        public string ThemeFile { get; set; }
        public bool UseSingleSignOn { get; set; }
        public string TextEditor { get; set; }
        public bool OverrideDefaultThemes { get; set; }
        public bool PMNotification { get; set; }
        public bool AutoWatchTopics { get; set; }
        public bool DailyDigest { get; set; }
        public Nullable<int> NotificationType { get; set; }
        public int Flags { get; set; }
        public int Points { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsGuest { get; set; }
        public Nullable<bool> IsCaptchaExcluded { get; set; }
        public Nullable<bool> IsActiveExcluded { get; set; }
        public Nullable<bool> IsDST { get; set; }
        public Nullable<bool> IsDirty { get; set; }
        public string Culture { get; set; }
        public bool IsFacebookUser { get; set; }
        public bool IsTwitterUser { get; set; }
        public string UserStyle { get; set; }
        public int StyleFlags { get; set; }
        public Nullable<bool> IsUserStyle { get; set; }
        public Nullable<bool> IsGroupStyle { get; set; }
        public Nullable<bool> IsRankStyle { get; set; }
    
        public virtual ICollection<yaf_Active> yaf_Active { get; set; }
        public virtual ICollection<yaf_AdminPageUserAccess> yaf_AdminPageUserAccess { get; set; }
        public virtual yaf_Board yaf_Board { get; set; }
        public virtual ICollection<yaf_Buddy> yaf_Buddy { get; set; }
        public virtual ICollection<yaf_CheckEmail> yaf_CheckEmail { get; set; }
        public virtual ICollection<yaf_EventLog> yaf_EventLog { get; set; }
        public virtual ICollection<yaf_FavoriteTopic> yaf_FavoriteTopic { get; set; }
        public virtual ICollection<yaf_Forum> yaf_Forum { get; set; }
        public virtual ICollection<yaf_ForumReadTracking> yaf_ForumReadTracking { get; set; }
        public virtual ICollection<yaf_Message> yaf_Message { get; set; }
        public virtual ICollection<yaf_PMessage> yaf_PMessage { get; set; }
        public virtual yaf_Rank yaf_Rank { get; set; }
        public virtual ICollection<yaf_ReputationVote> yaf_ReputationVote { get; set; }
        public virtual ICollection<yaf_ReputationVote> yaf_ReputationVote1 { get; set; }
        public virtual ICollection<yaf_Thanks> yaf_Thanks { get; set; }
        public virtual ICollection<yaf_Topic> yaf_Topic { get; set; }
        public virtual ICollection<yaf_Topic> yaf_Topic1 { get; set; }
        public virtual ICollection<yaf_TopicReadTracking> yaf_TopicReadTracking { get; set; }
        public virtual ICollection<yaf_UserForum> yaf_UserForum { get; set; }
        public virtual ICollection<yaf_UserMedal> yaf_UserMedal { get; set; }
        public virtual ICollection<yaf_UserPMessage> yaf_UserPMessage { get; set; }
        public virtual ICollection<yaf_UserProfile> yaf_UserProfile { get; set; }
        public virtual ICollection<yaf_WatchForum> yaf_WatchForum { get; set; }
        public virtual ICollection<yaf_WatchTopic> yaf_WatchTopic { get; set; }
        public virtual ICollection<yaf_Group> yaf_Group { get; set; }
    }
}
