//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VZF.Types.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yaf_WatchTopic
    {
        public int WatchTopicID { get; set; }
        public int TopicID { get; set; }
        public int UserID { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> LastMail { get; set; }
    
        public virtual yaf_Topic yaf_Topic { get; set; }
        public virtual yaf_User yaf_User { get; set; }
    }
}
