//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VZF.Types.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yaf_AccessMask
    {
        public yaf_AccessMask()
        {
            this.yaf_ForumAccess = new HashSet<yaf_ForumAccess>();
            this.yaf_UserForum = new HashSet<yaf_UserForum>();
        }
    
        public int AccessMaskID { get; set; }
        public int BoardID { get; set; }
        public string Name { get; set; }
        public int Flags { get; set; }
        public short SortOrder { get; set; }
    
        public virtual yaf_Board yaf_Board { get; set; }
        public virtual ICollection<yaf_ForumAccess> yaf_ForumAccess { get; set; }
        public virtual ICollection<yaf_UserForum> yaf_UserForum { get; set; }
    }
}
