//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VZF.Types.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yaf_Active
    {
        public string SessionID { get; set; }
        public int BoardID { get; set; }
        public int UserID { get; set; }
        public string IP { get; set; }
        public System.DateTime Login { get; set; }
        public System.DateTime LastActive { get; set; }
        public string Location { get; set; }
        public Nullable<int> ForumID { get; set; }
        public Nullable<int> TopicID { get; set; }
        public string Browser { get; set; }
        public string Platform { get; set; }
        public Nullable<int> Flags { get; set; }
        public string ForumPage { get; set; }
    
        public virtual yaf_Board yaf_Board { get; set; }
        public virtual yaf_Forum yaf_Forum { get; set; }
        public virtual yaf_Topic yaf_Topic { get; set; }
        public virtual yaf_User yaf_User { get; set; }
    }
}
