//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VZF.Types.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yaf_BBCode
    {
        public int BBCodeID { get; set; }
        public int BoardID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string OnClickJS { get; set; }
        public string DisplayJS { get; set; }
        public string EditJS { get; set; }
        public string DisplayCSS { get; set; }
        public string SearchRegex { get; set; }
        public string ReplaceRegex { get; set; }
        public string Variables { get; set; }
        public Nullable<bool> UseModule { get; set; }
        public string ModuleClass { get; set; }
        public int ExecOrder { get; set; }
    
        public virtual yaf_Board yaf_Board { get; set; }
    }
}
