//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VZF.Types.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yaf_Category
    {
        public yaf_Category()
        {
            this.yaf_Forum = new HashSet<yaf_Forum>();
        }
    
        public int CategoryID { get; set; }
        public int BoardID { get; set; }
        public string Name { get; set; }
        public string CategoryImage { get; set; }
        public short SortOrder { get; set; }
        public Nullable<int> PollGroupID { get; set; }
    
        public virtual yaf_Board yaf_Board { get; set; }
        public virtual yaf_PollGroupCluster yaf_PollGroupCluster { get; set; }
        public virtual ICollection<yaf_Forum> yaf_Forum { get; set; }
    }
}
