//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VZF.Types.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yaf_EventLogGroupAccess
    {
        public int GroupID { get; set; }
        public int EventTypeID { get; set; }
        public string EventTypeName { get; set; }
        public bool DeleteAccess { get; set; }
    
        public virtual yaf_Group yaf_Group { get; set; }
    }
}
