//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VZF.Types.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yaf_MessageHistory
    {
        public int MessageID { get; set; }
        public string Message { get; set; }
        public string IP { get; set; }
        public System.DateTime Edited { get; set; }
        public Nullable<int> EditedBy { get; set; }
        public string EditReason { get; set; }
        public bool IsModeratorChanged { get; set; }
        public int Flags { get; set; }
    
        public virtual yaf_Message yaf_Message { get; set; }
    }
}
