//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VZF.Types.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yaf_MessageReportedAudit
    {
        public int LogID { get; set; }
        public Nullable<int> UserID { get; set; }
        public int MessageID { get; set; }
        public Nullable<System.DateTime> Reported { get; set; }
        public int ReportedNumber { get; set; }
        public string ReportText { get; set; }
    
        public virtual yaf_MessageReported yaf_MessageReported { get; set; }
    }
}
