//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VZF.Types.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yaf_NntpForum
    {
        public yaf_NntpForum()
        {
            this.yaf_NntpTopic = new HashSet<yaf_NntpTopic>();
        }
    
        public int NntpForumID { get; set; }
        public int NntpServerID { get; set; }
        public string GroupName { get; set; }
        public int ForumID { get; set; }
        public int LastMessageNo { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> DateCutOff { get; set; }
    
        public virtual yaf_Forum yaf_Forum { get; set; }
        public virtual yaf_NntpServer yaf_NntpServer { get; set; }
        public virtual ICollection<yaf_NntpTopic> yaf_NntpTopic { get; set; }
    }
}
