//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VZF.Types.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yaf_NntpServer
    {
        public yaf_NntpServer()
        {
            this.yaf_NntpForum = new HashSet<yaf_NntpForum>();
        }
    
        public int NntpServerID { get; set; }
        public int BoardID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public Nullable<int> Port { get; set; }
        public string UserName { get; set; }
        public string UserPass { get; set; }
    
        public virtual yaf_Board yaf_Board { get; set; }
        public virtual ICollection<yaf_NntpForum> yaf_NntpForum { get; set; }
    }
}
