//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VZF.Types.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yaf_PMessage
    {
        public yaf_PMessage()
        {
            this.yaf_UserPMessage = new HashSet<yaf_UserPMessage>();
        }
    
        public int PMessageID { get; set; }
        public int FromUserID { get; set; }
        public System.DateTime Created { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public int Flags { get; set; }
        public Nullable<int> ReplyTo { get; set; }
    
        public virtual yaf_User yaf_User { get; set; }
        public virtual ICollection<yaf_UserPMessage> yaf_UserPMessage { get; set; }
    }
}
