//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VZF.Types.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yaf_Poll
    {
        public yaf_Poll()
        {
            this.yaf_Choice = new HashSet<yaf_Choice>();
            this.yaf_PollVote = new HashSet<yaf_PollVote>();
        }
    
        public int PollID { get; set; }
        public string Question { get; set; }
        public Nullable<System.DateTime> Closes { get; set; }
        public Nullable<int> PollGroupID { get; set; }
        public int UserID { get; set; }
        public string ObjectPath { get; set; }
        public string MimeType { get; set; }
        public int Flags { get; set; }
        public Nullable<bool> IsClosedBound { get; set; }
        public Nullable<bool> AllowMultipleChoices { get; set; }
        public Nullable<bool> ShowVoters { get; set; }
        public Nullable<bool> AllowSkipVote { get; set; }
    
        public virtual ICollection<yaf_Choice> yaf_Choice { get; set; }
        public virtual yaf_PollGroupCluster yaf_PollGroupCluster { get; set; }
        public virtual ICollection<yaf_PollVote> yaf_PollVote { get; set; }
    }
}
