//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VZF.Types.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yaf_PollVote
    {
        public int PollVoteID { get; set; }
        public int PollID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string RemoteIP { get; set; }
        public Nullable<int> ChoiceID { get; set; }
    
        public virtual yaf_Poll yaf_Poll { get; set; }
    }
}
