//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VZF.Types.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yaf_PollGroupCluster
    {
        public yaf_PollGroupCluster()
        {
            this.yaf_Category = new HashSet<yaf_Category>();
            this.yaf_Forum = new HashSet<yaf_Forum>();
            this.yaf_Poll = new HashSet<yaf_Poll>();
            this.yaf_Topic = new HashSet<yaf_Topic>();
        }
    
        public int PollGroupID { get; set; }
        public int UserID { get; set; }
        public int Flags { get; set; }
        public Nullable<bool> IsBound { get; set; }
    
        public virtual ICollection<yaf_Category> yaf_Category { get; set; }
        public virtual ICollection<yaf_Forum> yaf_Forum { get; set; }
        public virtual ICollection<yaf_Poll> yaf_Poll { get; set; }
        public virtual ICollection<yaf_Topic> yaf_Topic { get; set; }
    }
}
