//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VZF.Types.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yaf_prov_Application
    {
        public System.Guid ApplicationID { get; set; }
        public string ApplicationName { get; set; }
        public string ApplicationNameLwd { get; set; }
        public string Description { get; set; }
    }
}
