//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VZF.Types.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yaf_Rank
    {
        public yaf_Rank()
        {
            this.yaf_User = new HashSet<yaf_User>();
        }
    
        public int RankID { get; set; }
        public int BoardID { get; set; }
        public string Name { get; set; }
        public Nullable<int> MinPosts { get; set; }
        public string RankImage { get; set; }
        public int Flags { get; set; }
        public int PMLimit { get; set; }
        public string Style { get; set; }
        public short SortOrder { get; set; }
        public string Description { get; set; }
        public int UsrSigChars { get; set; }
        public string UsrSigBBCodes { get; set; }
        public string UsrSigHTMLTags { get; set; }
        public int UsrAlbums { get; set; }
        public int UsrAlbumImages { get; set; }
    
        public virtual yaf_Board yaf_Board { get; set; }
        public virtual ICollection<yaf_User> yaf_User { get; set; }
    }
}
