//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VZF.Types.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yaf_ReputationVote
    {
        public int ReputationFromUserID { get; set; }
        public int ReputationToUserID { get; set; }
        public System.DateTime VoteDate { get; set; }
    
        public virtual yaf_User yaf_User { get; set; }
        public virtual yaf_User yaf_User1 { get; set; }
    }
}
