//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VZF.Types.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yaf_ShoutboxMessage
    {
        public int ShoutBoxMessageID { get; set; }
        public int BoardId { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UserName { get; set; }
        public string Message { get; set; }
        public System.DateTime Date { get; set; }
        public string IP { get; set; }
        public string UserDisplayName { get; set; }
    }
}
