//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VZF.Types.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yaf_Smiley
    {
        public int SmileyID { get; set; }
        public int BoardID { get; set; }
        public string Code { get; set; }
        public string Icon { get; set; }
        public string Emoticon { get; set; }
        public byte SortOrder { get; set; }
    
        public virtual yaf_Board yaf_Board { get; set; }
    }
}
