//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VZF.Types.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yaf_Thanks
    {
        public int ThanksID { get; set; }
        public int ThanksFromUserID { get; set; }
        public int ThanksToUserID { get; set; }
        public int MessageID { get; set; }
        public System.DateTime ThanksDate { get; set; }
    
        public virtual yaf_User yaf_User { get; set; }
    }
}
