//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VZF.Types.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yaf_TopicStatus
    {
        public int TopicStatusID { get; set; }
        public string TopicStatusName { get; set; }
        public int BoardID { get; set; }
        public string DefaultDescription { get; set; }
    }
}
