//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VZF.Types.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yaf_UserAlbum
    {
        public yaf_UserAlbum()
        {
            this.yaf_UserAlbumImage = new HashSet<yaf_UserAlbumImage>();
        }
    
        public int AlbumID { get; set; }
        public int UserID { get; set; }
        public string Title { get; set; }
        public Nullable<int> CoverImageID { get; set; }
        public System.DateTime Updated { get; set; }
    
        public virtual ICollection<yaf_UserAlbumImage> yaf_UserAlbumImage { get; set; }
    }
}
