//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VZF.Types.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yaf_UserAlbumImage
    {
        public int ImageID { get; set; }
        public int AlbumID { get; set; }
        public string Caption { get; set; }
        public string FileName { get; set; }
        public int Bytes { get; set; }
        public string ContentType { get; set; }
        public System.DateTime Uploaded { get; set; }
        public int Downloads { get; set; }
    
        public virtual yaf_UserAlbum yaf_UserAlbum { get; set; }
    }
}
