EXECUTE BLOCK
AS
BEGIN
EXECUTE STATEMENT 'UPDATE {objectQualifier}GROUP SET STYLE = NULL WHERE STYLE IS NOT NULL AND CHAR_LENGTH(STYLE) <=2;';
EXECUTE STATEMENT 'UPDATE {objectQualifier}RANK SET STYLE = NULL WHERE STYLE IS NOT NULL AND CHAR_LENGTH(STYLE) <=2;';
EXECUTE STATEMENT 'UPDATE {objectQualifier}RANK SET FLAGS = BIN_OR(FLAGS, 4) WHERE NAME LIKE ''Guest'';';
END
--GO