EXECUTE BLOCK
AS
BEGIN
EXECUTE STATEMENT 'UPDATE objQual_GROUP SET STYLE = NULL WHERE STYLE IS NOT NULL AND CHAR_LENGTH(STYLE) <=2;';
EXECUTE STATEMENT 'UPDATE objQual_RANK SET STYLE = NULL WHERE STYLE IS NOT NULL AND CHAR_LENGTH(STYLE) <=2;';
EXECUTE STATEMENT 'UPDATE objQual_RANK SET FLAGS = BIN_OR(FLAGS, 4) WHERE NAME LIKE ''Guest'';';
END
--GO