//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VZF.Types.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yaf_vaccess
    {
        public int UserID { get; set; }
        public Nullable<int> ForumID { get; set; }
        public Nullable<int> IsAdmin { get; set; }
        public Nullable<int> IsForumModerator { get; set; }
        public Nullable<int> IsModerator { get; set; }
        public Nullable<int> ReadAccess { get; set; }
        public Nullable<int> PostAccess { get; set; }
        public Nullable<int> ReplyAccess { get; set; }
        public Nullable<int> PriorityAccess { get; set; }
        public Nullable<int> PollAccess { get; set; }
        public Nullable<int> VoteAccess { get; set; }
        public Nullable<int> ModeratorAccess { get; set; }
        public Nullable<int> EditAccess { get; set; }
        public Nullable<int> DeleteAccess { get; set; }
        public Nullable<int> UploadAccess { get; set; }
        public Nullable<int> DownloadAccess { get; set; }
    }
}
