/* Yet Another Forum.NET Firebird data layer by vzrus
 * Copyright (C) 2006-2014 Vladimir Zakharov
 * https://github.com/vzrus
 * http://sourceforge.net/projects/yaf-datalayers/
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; version 2 only
 * General class structure is based on MS SQL Server code,
 * created by YAF developers
 *
 * http://www.yetanotherforum.net/
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation;version 2 only
 * of the License.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
EXECUTE BLOCK
AS
BEGIN
-- Source foreign key: FK_{objectQualifier}ACCESSMASK_BOARD
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}ACCESSMASK_BOARD') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}ACCESSMASK')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}ACCESSMASK ADD CONSTRAINT FK_{objectQualifier}ACCESSMASK_BOARD FOREIGN KEY (BOARDID) REFERENCES {objectQualifier}BOARD(BOARDID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source foreign key: FK_{objectQualifier}TAGS_TOPICTAGS
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}TAGS_TOPICTAGS') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}TOPICTAGS')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}TOPICTAGS ADD CONSTRAINT FK_{objectQualifier}TAGS_TOPICTAGS FOREIGN KEY (TAGID) REFERENCES {objectQualifier}TAGS(TAGID) ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO


EXECUTE BLOCK
AS
BEGIN
-- Source foreign key: FK_{objectQualifier}TOPIC_TOPICTAGS
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}TOPIC_TOPICTAGS') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}TOPICTAGS')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}TOPICTAGS ADD CONSTRAINT FK_{objectQualifier}TOPIC_TOPICTAGS FOREIGN KEY (TOPICID) REFERENCES {objectQualifier}TOPIC(TOPICID) ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source foreign key: FK_{objectQualifier}ACTIVE_BOARD
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}ACTIVE_BOARD') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}ACTIVE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}ACTIVE ADD CONSTRAINT FK_{objectQualifier}ACTIVE_BOARD FOREIGN KEY (BOARDID) REFERENCES {objectQualifier}BOARD(BOARDID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO


EXECUTE BLOCK
AS
BEGIN
-- Source foreign key: FK_{objectQualifier}ACTIVE_FORUM
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}ACTIVE_FORUM') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}ACTIVE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}ACTIVE ADD CONSTRAINT FK_{objectQualifier}ACTIVE_FORUM FOREIGN KEY (FORUMID) REFERENCES {objectQualifier}FORUM(FORUMID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_{objectQualifier}ACTIVE_TOPIC
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}ACTIVE_TOPIC') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}ACTIVE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}ACTIVE ADD CONSTRAINT FK_{objectQualifier}ACTIVE_TOPIC FOREIGN KEY (TOPICID) REFERENCES {objectQualifier}TOPIC(TOPICID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_{objectQualifier}ACTIVE_USER
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}ACTIVE_USER') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}ACTIVE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}ACTIVE ADD CONSTRAINT FK_{objectQualifier}ACTIVE_USER FOREIGN KEY (USERID) REFERENCES {objectQualifier}USER(USERID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_{objectQualifier}ATTACHMENT_MESSAGE

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}ATTACHMENT_MESSAGE') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}ATTACHMENT')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}ATTACHMENT ADD CONSTRAINT FK_{objectQualifier}ATTACHMENT_MESSAGE FOREIGN KEY (MESSAGEID) REFERENCES {objectQualifier}MESSAGE(MESSAGEID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_{objectQualifier}BANNEDIP_BOARDID
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}BANNEDIP_BOARDID') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}BANNEDIP')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}BANNEDIP ADD CONSTRAINT FK_{objectQualifier}BANNEDIP_BOARDID FOREIGN KEY (BOARDID) REFERENCES {objectQualifier}BOARD(BOARDID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_{objectQualifier}BBCODE_BOARD
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}BBCODE_BOARD') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}BBCODE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}BBCODE ADD CONSTRAINT FK_{objectQualifier}BBCODE_BOARD FOREIGN KEY (BOARDID) REFERENCES {objectQualifier}BOARD(BOARDID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_{objectQualifier}CATEGORY_BOARD

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}CATEGORY_BOARD') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}CATEGORY')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}CATEGORY ADD CONSTRAINT FK_{objectQualifier}CATEGORY_BOARD FOREIGN KEY (BOARDID) REFERENCES {objectQualifier}BOARD(BOARDID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_{objectQualifier}CHECKEMAIL_USER
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}CHECKEMAIL_USER') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}CHECKEMAIL')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}CHECKEMAIL ADD CONSTRAINT FK_{objectQualifier}CHECKEMAIL_USER FOREIGN KEY (USERID) REFERENCES {objectQualifier}USER(USERID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO



-- Source foreign key: FK_{objectQualifier}CHOICE_POLL
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}CHOICE_POLL') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}CHOICE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}CHOICE ADD CONSTRAINT FK_{objectQualifier}CHOICE_POLL FOREIGN KEY (POLLID) REFERENCES {objectQualifier}POLL(POLLID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO



-- Source foreign key: FK_{objectQualifier}EVENTLOG_USER
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}EVENTLOG_USER') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}EVENTLOG')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}EVENTLOG ADD CONSTRAINT FK_{objectQualifier}EVENTLOG_USER FOREIGN KEY (USERID) REFERENCES {objectQualifier}USER(USERID) ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_{objectQualifier}EXTENSION_BOARD
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}EXTENSION_BOARD') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}EXTENSION')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}EXTENSION ADD CONSTRAINT FK_{objectQualifier}EXTENSION_BOARD FOREIGN KEY (BOARDID) REFERENCES {objectQualifier}BOARD(BOARDID) ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_{objectQualifier}FORUM_CATEGORY
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}FORUM_CATEGORY') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}FORUM')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}FORUM ADD CONSTRAINT FK_{objectQualifier}FORUM_CATEGORY FOREIGN KEY (CATEGORYID) REFERENCES {objectQualifier}CATEGORY(CATEGORYID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_{objectQualifier}FORUM_FORUM
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}FORUM_FORUM') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}FORUM')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}FORUM ADD CONSTRAINT FK_{objectQualifier}FORUM_FORUM FOREIGN KEY (PARENTID) REFERENCES {objectQualifier}FORUM(FORUMID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_{objectQualifier}FORUM_MESSAGE
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}FORUM_MESSAGE') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}FORUM')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}FORUM ADD CONSTRAINT FK_{objectQualifier}FORUM_MESSAGE FOREIGN KEY (LASTMESSAGEID) REFERENCES {objectQualifier}MESSAGE(MESSAGEID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_{objectQualifier}FORUM_TOPIC
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}FORUM_TOPIC') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}FORUM')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}FORUM ADD CONSTRAINT FK_{objectQualifier}FORUM_TOPIC FOREIGN KEY (LASTTOPICID) REFERENCES {objectQualifier}TOPIC(TOPICID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_{objectQualifier}FORUM_USER
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}FORUM_USER') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}FORUM')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}FORUM ADD CONSTRAINT FK_{objectQualifier}FORUM_USER FOREIGN KEY (LASTUSERID) REFERENCES {objectQualifier}USER(USERID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO


-- Source foreign key: FK_{objectQualifier}FORUMACCESS_MASKccessMask
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}FORUMACCESS_MASK') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}FORUMACCESS')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}FORUMACCESS ADD CONSTRAINT FK_{objectQualifier}FORUMACCESS_MASK FOREIGN KEY (ACCESSMASKID) REFERENCES {objectQualifier}ACCESSMASK(ACCESSMASKID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_{objectQualifier}FORUMACCESS_FORUM
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}FORUMACCESS_FORUM') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}FORUMACCESS')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}FORUMACCESS ADD CONSTRAINT FK_{objectQualifier}FORUMACCESS_FORUM FOREIGN KEY (FORUMID) REFERENCES {objectQualifier}FORUM(FORUMID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_{objectQualifier}FORUMACCESS_GROUP
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}FORUMACCESS_GROUP') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}FORUMACCESS')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}FORUMACCESS ADD CONSTRAINT FK_{objectQualifier}FORUMACCESS_GROUP FOREIGN KEY (GROUPID) REFERENCES {objectQualifier}GROUP(GROUPID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_{objectQualifier}GROUP_BOARD
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}GROUP_BOARD') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}GROUP')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}GROUP ADD CONSTRAINT FK_{objectQualifier}GROUP_BOARD FOREIGN KEY (BOARDID) REFERENCES {objectQualifier}BOARD(BOARDID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO


-- Source foreign key: FK_{objectQualifier}MESSAGE_MESID_REPLYTO
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}MESSAGE_MESID_REPLYTO') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}MESSAGE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}MESSAGE ADD CONSTRAINT FK_{objectQualifier}MESSAGE_MESID_REPLYTO FOREIGN KEY (REPLYTO) REFERENCES {objectQualifier}MESSAGE(MESSAGEID) ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_{objectQualifier}MESSAGE_TOPIC
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}MESSAGE_TOPIC') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}MESSAGE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}MESSAGE ADD CONSTRAINT FK_{objectQualifier}MESSAGE_TOPIC FOREIGN KEY (TOPICID) REFERENCES {objectQualifier}TOPIC(TOPICID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_{objectQualifier}MESSAGE_USER
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}MESSAGE_USER') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}MESSAGE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}MESSAGE ADD CONSTRAINT FK_{objectQualifier}MESSAGE_USER FOREIGN KEY (USERID) REFERENCES {objectQualifier}USER(USERID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO



-- Source foreign key: TR_AI_{objectQualifier}NNTPFORUM_FORUMum
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'TR_AI_{objectQualifier}NNTPFORUM_FORUM') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}NNTPFORUM')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}NNTPFORUM ADD CONSTRAINT TR_AI_{objectQualifier}NNTPFORUM_FORUM FOREIGN KEY (FORUMID) REFERENCES {objectQualifier}FORUM(FORUMID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: TR_AI_{objectQualifier}NNTPFORUM_NNTPSERVpServer
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'TR_AI_{objectQualifier}NNTPFORUM_NNTPSERV') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}NNTPFORUM')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}NNTPFORUM ADD CONSTRAINT TR_AI_{objectQualifier}NNTPFORUM_NNTPSERV FOREIGN KEY (NNTPSERVERID) REFERENCES {objectQualifier}NNTPSERVER(NNTPSERVERID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO


-- Source foreign key: FK_{objectQualifier}NNTPSERVER_BOARD
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}NNTPSERVER_BOARD') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}NNTPSERVER')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}NNTPSERVER ADD CONSTRAINT FK_{objectQualifier}NNTPSERVER_BOARD FOREIGN KEY (BOARDID) REFERENCES {objectQualifier}BOARD(BOARDID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO


-- Source foreign key: FK_{objectQualifier}NNTPTOPIC_NNTPF
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}NNTPTOPIC_NNTPF') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}NNTPTOPIC')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}NNTPTOPIC ADD CONSTRAINT FK_{objectQualifier}NNTPTOPIC_NNTPF FOREIGN KEY (NNTPFORUMID) REFERENCES {objectQualifier}NNTPFORUM(NNTPFORUMID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_{objectQualifier}NNTPTOPIC_TOPICic
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}NNTPTOPIC_TOPIC') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}NNTPTOPIC')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}NNTPTOPIC ADD CONSTRAINT FK_{objectQualifier}NNTPTOPIC_TOPIC FOREIGN KEY (TOPICID) REFERENCES {objectQualifier}TOPIC(TOPICID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO



-- Source foreign key: FK_{objectQualifier}PMESSAGE_USER1
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}PMESSAGE_USER') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}PMESSAGE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}PMESSAGE ADD CONSTRAINT FK_{objectQualifier}PMESSAGE_USER FOREIGN KEY (FROMUSERID) REFERENCES {objectQualifier}USER(USERID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO


-- Source foreign key: FK_{objectQualifier}POLLVOTE_POLL
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}POLLVOTE_POLL') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}POLLVOTE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}POLLVOTE ADD CONSTRAINT FK_{objectQualifier}POLLVOTE_POLL FOREIGN KEY (POLLID) REFERENCES {objectQualifier}POLL(POLLID) ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO



-- Source foreign key: FK_{objectQualifier}RANK_BOARD
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}RANK_BOARD') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}RANK')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}RANK ADD CONSTRAINT FK_{objectQualifier}RANK_BOARD FOREIGN KEY (BOARDID) REFERENCES {objectQualifier}BOARD(BOARDID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO



-- Source foreign key: FK_{objectQualifier}REGISTRY_BOARDd
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}REGISTRY_BOARD') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}REGISTRY')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}REGISTRY ADD CONSTRAINT FK_{objectQualifier}REGISTRY_BOARD FOREIGN KEY (BOARDID) REFERENCES {objectQualifier}BOARD(BOARDID) ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO


-- Source foreign key: FK_{objectQualifier}SMILEY_BOARD
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}SMILEY_BOARD') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}SMILEY')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}SMILEY ADD CONSTRAINT FK_{objectQualifier}SMILEY_BOARD FOREIGN KEY (BOARDID) REFERENCES {objectQualifier}BOARD(BOARDID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO


-- Source foreign key: FK_{objectQualifier}TOPIC_FORUM
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}TOPIC_FORUM') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}TOPIC')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}TOPIC ADD CONSTRAINT FK_{objectQualifier}TOPIC_FORUM FOREIGN KEY (FORUMID) REFERENCES {objectQualifier}FORUM(FORUMID) ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_{objectQualifier}TOPIC_MESSAGE
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}TOPIC_MESSAGE') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}TOPIC')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}TOPIC ADD CONSTRAINT FK_{objectQualifier}TOPIC_MESSAGE FOREIGN KEY (LASTMESSAGEID) REFERENCES {objectQualifier}MESSAGE(MESSAGEID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_{objectQualifier}TOPIC_POLL
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}TOPIC_POLL') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}TOPIC')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}TOPIC ADD CONSTRAINT FK_{objectQualifier}TOPIC_POLL FOREIGN KEY (POLLID) REFERENCES {objectQualifier}POLLGROUPCLUSTER(POLLGROUPID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_{objectQualifier}TOPIC_TOPIC
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}TOPIC_TOPIC') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}TOPIC')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}TOPIC ADD CONSTRAINT FK_{objectQualifier}TOPIC_TOPIC FOREIGN KEY (TOPICMOVEDID) REFERENCES {objectQualifier}TOPIC(TOPICID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_{objectQualifier}TOPIC_USER
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}TOPIC_USER') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}TOPIC')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}TOPIC ADD CONSTRAINT FK_{objectQualifier}TOPIC_USER FOREIGN KEY (USERID) REFERENCES {objectQualifier}USER(USERID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_{objectQualifier}TOPIC_USER_2
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}TOPIC_USER_2') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}TOPIC')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}TOPIC ADD CONSTRAINT FK_{objectQualifier}TOPIC_USER_2 FOREIGN KEY (LASTUSERID) REFERENCES {objectQualifier}USER(USERID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_{objectQualifier}USER_BOARD
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}USER_BOARD') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}USER')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}USER ADD CONSTRAINT FK_{objectQualifier}USER_BOARD FOREIGN KEY (BOARDID) REFERENCES {objectQualifier}BOARD(BOARDID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_{objectQualifier}USER_RANK
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}USER_RANK') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}USER')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}USER ADD CONSTRAINT FK_{objectQualifier}USER_RANK FOREIGN KEY (RANKID) REFERENCES {objectQualifier}RANK(RANKID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO



-- Source foreign key: FK_{objectQualifier}USERFORUM_ACCMessMask
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}USERFORUM_ACCM') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}USERFORUM')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}USERFORUM ADD CONSTRAINT FK_{objectQualifier}USERFORUM_ACCM FOREIGN KEY (ACCESSMASKID) REFERENCES {objectQualifier}ACCESSMASK(ACCESSMASKID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_{objectQualifier}USERFORUM_FORUMum
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}USERFORUM_FORUM') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}USERFORUM')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}USERFORUM ADD CONSTRAINT FK_{objectQualifier}USERFORUM_FORUM FOREIGN KEY (FORUMID) REFERENCES {objectQualifier}FORUM(FORUMID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_{objectQualifier}USERFORUM_USERr
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}USERFORUM_USER') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}USERFORUM')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}USERFORUM ADD CONSTRAINT FK_{objectQualifier}USERFORUM_USER FOREIGN KEY (USERID) REFERENCES {objectQualifier}USER(USERID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_{objectQualifier}USERGROUP_GROUPup
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}USERGROUP_GROUP') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}USERGROUP')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}USERGROUP ADD CONSTRAINT FK_{objectQualifier}USERGROUP_GROUP FOREIGN KEY (GROUPID) REFERENCES {objectQualifier}GROUP(GROUPID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_{objectQualifier}USERGROUP_USERr
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}USERGROUP_USER') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}USERGROUP')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}USERGROUP ADD CONSTRAINT FK_{objectQualifier}USERGROUP_USER FOREIGN KEY (USERID) REFERENCES {objectQualifier}USER(USERID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_{objectQualifier}USERPMESSAGE_PMPMessage
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}USERPMESSAGE_PM') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}USERPMESSAGE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}USERPMESSAGE ADD CONSTRAINT FK_{objectQualifier}USERPMESSAGE_PM FOREIGN KEY (PMESSAGEID) REFERENCES {objectQualifier}PMESSAGE(PMESSAGEID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_{objectQualifier}USERPMESSAGE_PMUser
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}USERPMESSAGE_PMU') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}USERPMESSAGE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}USERPMESSAGE ADD CONSTRAINT FK_{objectQualifier}USERPMESSAGE_PMU FOREIGN KEY (USERID) REFERENCES {objectQualifier}USER(USERID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO



-- Source foreign key: FK_{objectQualifier}WATCHFORUM1_FORUM
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}WATCHFORUM1_FORUM') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}WATCHFORUM')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}WATCHFORUM ADD CONSTRAINT FK_{objectQualifier}WATCHFORUM1_FORUM FOREIGN KEY (FORUMID) REFERENCES {objectQualifier}FORUM(FORUMID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_{objectQualifier}WatchForum1_{objectQualifier}User
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}WATCHFORUM1_USER') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}WATCHFORUM')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}WATCHFORUM ADD CONSTRAINT FK_{objectQualifier}WATCHFORUM1_USER FOREIGN KEY (USERID) REFERENCES {objectQualifier}USER(USERID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO



-- Source foreign key: FK_{objectQualifier}WATCHTOPIC_TOPIC
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}WATCHTOPIC_TOPIC') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}WATCHTOPIC')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}WATCHTOPIC ADD CONSTRAINT FK_{objectQualifier}WATCHTOPIC_TOPIC FOREIGN KEY (TOPICID) REFERENCES {objectQualifier}TOPIC(TOPICID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_{objectQualifier}WatchTopic_{objectQualifier}User
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}WATCHTOPIC_USER') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}WATCHTOPIC')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}WATCHTOPIC ADD CONSTRAINT FK_{objectQualifier}WATCHTOPIC_USER FOREIGN KEY (USERID) REFERENCES {objectQualifier}USER(USERID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO


-- Source foreign key: FK_{objectQualifier}MSGHIS_MSGHISID
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}MSGHIS_MSGHISID') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}MESSAGEHISTORY')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}MESSAGEHISTORY 
   ADD CONSTRAINT FK_{objectQualifier}MSGHIS_MSGHISID 
   FOREIGN KEY (MESSAGEID) REFERENCES {objectQualifier}MESSAGE(MESSAGEID) 
   ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}USRPROF_USRID') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}USERPROFILE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}USERPROFILE 
   ADD CONSTRAINT FK_{objectQualifier}USRPROF_USRID 
   FOREIGN KEY (USERID) REFERENCES {objectQualifier}USER(USERID) 
   ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}MSGREPAUD_MSGREP') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}MESSAGEREPORTEDAUDIT')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}MESSAGEREPORTEDAUDIT 
   ADD CONSTRAINT FK_{objectQualifier}MSGREPAUD_MSGREP 
   FOREIGN KEY (MESSAGEID) REFERENCES {objectQualifier}MESSAGEREPORTED(MESSAGEID) 
   ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}FORUMREADTRACKING_USERID') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}FORUMREADTRACKING')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}FORUMREADTRACKING 
   ADD CONSTRAINT FK_{objectQualifier}FORUMREADTRACKING_USERID 
   FOREIGN KEY (USERID) REFERENCES {objectQualifier}USER(USERID) 
   ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}FORUMREADTRACKING_FRMID') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}FORUMREADTRACKING')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}FORUMREADTRACKING 
   ADD CONSTRAINT FK_{objectQualifier}FORUMREADTRACKING_FRMID 
   FOREIGN KEY (FORUMID) REFERENCES {objectQualifier}FORUM(FORUMID) 
   ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}TOPICREADTRACKING_TOPID') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}TOPICREADTRACKING')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}TOPICREADTRACKING 
   ADD CONSTRAINT FK_{objectQualifier}TOPICREADTRACKING_TOPID 
   FOREIGN KEY (TOPICID) REFERENCES {objectQualifier}TOPIC(TOPICID) 
   ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}FORUMREADTRACKING_FRMID') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}FORUMREADTRACKING')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}FORUMREADTRACKING 
   ADD CONSTRAINT FK_{objectQualifier}FORUMREADTRACKING_FRMID 
   FOREIGN KEY (FORUMID) REFERENCES {objectQualifier}FORUM(FORUMID) 
   ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO


EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}REPUTATIONVOTE_FROMUSER') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}REPUTATIONVOTE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}REPUTATIONVOTE 
   ADD CONSTRAINT FK_{objectQualifier}REPUTATIONVOTE_FROMUSER 
   FOREIGN KEY (REPUTATIONFROMUSERID) REFERENCES {objectQualifier}USER(USERID) 
   ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}REPUTATIONVOTE_TOUSER') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}REPUTATIONVOTE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}REPUTATIONVOTE 
   ADD CONSTRAINT FK_{objectQualifier}REPUTATIONVOTE_TOUSER 
   FOREIGN KEY (REPUTATIONTOUSERID) REFERENCES {objectQualifier}USER(USERID) 
   ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}ADMPGUSRACCESS_USERID') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}ADMINPAGEUSERACCESS')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}ADMINPAGEUSERACCESS 
   ADD CONSTRAINT FK_{objectQualifier}ADMPGUSRACCESS_USERID 
   FOREIGN KEY (USERID) REFERENCES {objectQualifier}USER(USERID) 
   ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}ELOGGROUPACCESS_GROUPID') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}EVENTLOGGROUPACCESS')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}EVENTLOGGROUPACCESS 
   ADD CONSTRAINT FK_{objectQualifier}ELOGGROUPACCESS_GROUPID 
   FOREIGN KEY (GROUPID) REFERENCES {objectQualifier}GROUP(GROUPID) 
   ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}GROUPHISTORY_GROUPID') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}GROUPHISTORY')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}GROUPHISTORY 
   ADD CONSTRAINT FK_{objectQualifier}GROUPHISTORY_GROUPID 
   FOREIGN KEY (GROUPID) REFERENCES {objectQualifier}GROUP(GROUPID) 
   ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}FORUMHISTORY_FORUMID') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}FORUMHISTORY')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}FORUMHISTORY 
   ADD CONSTRAINT FK_{objectQualifier}FORUMHISTORY_FORUMID 
   FOREIGN KEY (FORUMID) REFERENCES {objectQualifier}FORUM(FORUMID) 
   ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_{objectQualifier}ACSMASKHIST_ACSMASKID') 
    AND (RC.RDB$RELATION_NAME = '{objectQualifier}ACCESSMASKHISTORY')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE {objectQualifier}ACCESSMASKHISTORY 
   ADD CONSTRAINT FK_{objectQualifier}ACSMASKHIST_ACSMASKID 
   FOREIGN KEY (ACCESSMASKID) REFERENCES {objectQualifier}ACCESSMASK(ACCESSMASKID) 
   ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO


