
/* Yet Another Forum.NET Firebird data layer by vzrus
 * Copyright (C) 2006-2014 Vladimir Zakharov
 * https://github.com/vzrus
 * http://sourceforge.net/projects/yaf-datalayers/
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; version 2 only
 * General class structure is based on MS SQL Server code,
 * created by YAF developers
 *
 * http://www.yetanotherforum.net/
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation;version 2 only
 * of the License.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}DBINFO_TABLE_COLUMNS_INFO')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}DBINFO_TABLE_COLUMNS_INFO;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_SAVENOTIFICATION')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_SAVENOTIFICATION;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}FORUM_MAXID')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}FORUM_MAXID;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}FORUM_SAVE_PRNTCHCK')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}FORUM_SAVE_PRNTCHCK';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}TOPIC_UNANSWERED')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}TOPIC_UNANSWERED;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}TOPIC_TAGS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}TOPIC_TAGS;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}FORUM_TAGS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}FORUM_TAGS;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}TOPIC_BYTAGS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}TOPIC_BYTAGS;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_UPDATE_SSN_STATUS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_UPDATE_SSN_STATUS;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}ANNOUNCEMENTS_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}ANNOUNCEMENTS_LIST;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}ACCESSMASK_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}ACCESSMASK_DELETE;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}THANKFROMCOUNT')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}THANKFROMCOUNT;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_REPLIEDTOPIC')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_REPLIEDTOPIC;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}ADMIN_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}ADMIN_LIST;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}ACCESSMASK_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}ACCESSMASK_LIST;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}FORUM_CATACCESS_ACTUSER')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}FORUM_CATACCESS_ACTUSER;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}ACCESSMASK_SEARCHLIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}ACCESSMASK_SEARCHLIST;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}ACCESSMASK_PFORUMLIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}ACCESSMASK_PFORUMLIST;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}ACCESSMASK_AFORUMLIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}ACCESSMASK_AFORUMLIST;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}ACCESSMASK_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}ACCESSMASK_SAVE;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}ACTIVE_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}ACTIVE_LIST;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}ACTIVE_LIST_USER')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}ACTIVE_LIST_USER;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}ACTIVE_LISTFORUM')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}ACTIVE_LISTFORUM;';  
END

--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}ACTIVE_LISTTOPIC')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}ACTIVE_LISTTOPIC;';  
END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}ACTIVE_STATS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}ACTIVE_STATS;';  
END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}ATTACHMENT_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}ATTACHMENT_DELETE;';  
END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}ATTACHMENT_DOWNLOAD')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}ATTACHMENT_DOWNLOAD;';  
END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}ATTACHMENT_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}ATTACHMENT_LIST;';  
END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}ATTACHMENT_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}ATTACHMENT_SAVE;';  
END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}BANNEDIP_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}BANNEDIP_DELETE;';  
END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}BANNEDIP_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}BANNEDIP_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}BANNEDIP_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}BANNEDIP_SAVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}BBCODE_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}BBCODE_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}BBCODE_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}BBCODE_SAVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}BBCODE_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}BBCODE_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}BOARD_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}BOARD_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}BOARD_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}BOARD_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}BOARD_POSTSTATS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}BOARD_POSTSTATS;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}BOARD_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}BOARD_SAVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}BOARD_STATS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}BOARD_STATS;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}BOARD_RESYNC')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}BOARD_RESYNC;';  END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}SYSTEM_UPDATEVERSION')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}SYSTEM_UPDATEVERSION;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}SYSTEM_INITIALIZE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}SYSTEM_INITIALIZE;';  END
--GO



EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}EVENTLOG_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}EVENTLOG_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}EXTENSION_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}EXTENSION_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}EXTENSION_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}EXTENSION_SAVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}PAGELOAD')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}PAGELOAD;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}REGISTRY_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}REGISTRY_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}FORUM_MODERATORS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}FORUM_MODERATORS;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}MODERATORS_TEAM_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}MODERATORS_TEAM_LIST;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}CATEGORY_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}CATEGORY_LIST;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}CATEGORY_PFACCESSLIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}CATEGORY_PFACCESSLIST;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}CATEGORY_GETADJACENTFORUM')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}CATEGORY_GETADJACENTFORUM;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}FORUM_LISTREAD')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}FORUM_LISTREAD;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}FORUM_NS_LISTREAD')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}FORUM_NS_LISTREAD;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}FORUM_LISTREAD_HELPER')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}FORUM_LISTREAD_HELPER;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}FORUM_LISTREADPERSONAL')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}FORUM_LISTREADPERSONAL;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}TOPIC_LATEST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}TOPIC_LATEST;';  END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_GUEST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_GUEST;';  END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}FORUM_LISTPATH')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}FORUM_LISTPATH;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}FORUM_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}FORUM_LIST;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}FORUM_BYUSERLIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}FORUM_BYUSERLIST;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}TOPIC_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}TOPIC_LIST;';  END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}CATEGORY_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}CATEGORY_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}CATEGORY_LISTREAD')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}CATEGORY_LISTREAD;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}CATEGORY_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}CATEGORY_SAVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}CATEGORY_SIMPLELIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}CATEGORY_SIMPLELIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}CHECKEMAIL_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}CHECKEMAIL_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}CHECKEMAIL_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}CHECKEMAIL_SAVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}CHECKEMAIL_UPDATE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}CHECKEMAIL_UPDATE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}CHOICE_ADD')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}CHOICE_ADD;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}CHOICE_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}CHOICE_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}CHOICE_UPDATE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}CHOICE_UPDATE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}CHOICE_VOTE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}CHOICE_VOTE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}EVENTLOG_CREATE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}EVENTLOG_CREATE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}EVENTLOG_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}EVENTLOG_DELETE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}EXTENSION_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}EXTENSION_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}EXTENSION_EDIT')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}EXTENSION_EDIT;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}FORUM_LISTALL')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}FORUM_LISTALL;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}FORUM_LISTALL_FROMCAT')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}FORUM_LISTALL_FROMCAT;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}FORUM_LISTALLMYMODERATED')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}FORUM_LISTALLMYMODERATED;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}FORUM_LISTSUBFORUMS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}FORUM_LISTSUBFORUMS;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}FORUM_LISTTOPICS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}FORUM_LISTTOPICS;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}FORUM_MODERATELIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}FORUM_MODERATELIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}FORUM_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}FORUM_SAVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}FORUM_SIMPLELIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}FORUM_SIMPLELIST;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}FORUMACCESS_GROUP')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}FORUMACCESS_GROUP;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}FORUMACCESS_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}FORUMACCESS_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}FORUMACCESS_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}FORUMACCESS_SAVE;';  END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}GROUP_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}GROUP_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}GROUP_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}GROUP_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}GROUP_BYUSERLIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}GROUP_BYUSERLIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}GROUP_MEDAL_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}GROUP_MEDAL_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}GROUP_MEDAL_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}GROUP_MEDAL_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}GROUP_MEMBER')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}GROUP_MEMBER;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}GROUP_MEDAL_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}GROUP_MEDAL_SAVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}GROUP_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}GROUP_SAVE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}GROUP_RANK_STYLE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}GROUP_RANK_STYLE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}MAIL_CREATE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}MAIL_CREATE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}MAIL_CREATEWATCH')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}MAIL_CREATEWATCH;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}MAIL_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}MAIL_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}MAIL_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}MAIL_LIST;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}MEDAL_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}MEDAL_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}MEDAL_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}MEDAL_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}MEDAL_LISTUSERS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}MEDAL_LISTUSERS;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}MEDAL_RESORT')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}MEDAL_RESORT;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}MEDAL_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}MEDAL_SAVE;';  END
--GO








EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}MESSAGE_DELETEUNDELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}MESSAGE_DELETEUNDELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}MESSAGE_FINDUNREAD')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}MESSAGE_FINDUNREAD;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}MESSAGE_GETREPLIES')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}MESSAGE_GETREPLIES;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}MESSAGE_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}MESSAGE_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}MESSAGE_LISTREPORTED')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}MESSAGE_LISTREPORTED;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}MESSAGE_LISTREPORTERS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}MESSAGE_LISTREPORTERS;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}MESSAGE_MOVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}MESSAGE_MOVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}MESSAGE_REPLY_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}MESSAGE_REPLY_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}MESSAGE_REPORT')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}MESSAGE_REPORT;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}MESSAGE_REPORTCOPYOVER')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}MESSAGE_REPORTCOPYOVER;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}MESSAGE_REPORTRESOLVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}MESSAGE_REPORTRESOLVE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}MESSAGE_SIMPLELIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}MESSAGE_SIMPLELIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}MESSAGE_UNAPPROVED')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}MESSAGE_UNAPPROVED;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}MESSAGE_UPDATE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}MESSAGE_UPDATE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}MESSAGE_UPDATE1')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}MESSAGE_UPDATE1;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}MESSAGE_UPDATE2')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}MESSAGE_UPDATE2;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}NNTPFORUM_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}NNTPFORUM_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}NNTPFORUM_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}NNTPFORUM_SAVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}NNTPFORUM_UPDATE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}NNTPFORUM_UPDATE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}NNTPSERVER_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}NNTPSERVER_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}NNTPSERVER_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}NNTPSERVER_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}NNTPSERVER_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}NNTPSERVER_SAVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}NNTPTOPIC_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}NNTPTOPIC_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}NNTPTOPIC_SAVEMESSAGE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}NNTPTOPIC_SAVEMESSAGE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}PMESSAGE_ARCHIVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}PMESSAGE_ARCHIVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}PMESSAGE_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}PMESSAGE_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}PMESSAGE_INFO')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}PMESSAGE_INFO;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}PMESSAGE_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}PMESSAGE_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}PMESSAGE_MARKREAD')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}PMESSAGE_MARKREAD;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}PMESSAGE_PRUNE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}PMESSAGE_PRUNE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}PMESSAGE_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}PMESSAGE_SAVE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}POLL_REMOVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}POLL_REMOVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}POLL_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}POLL_SAVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}POLL_STATS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}POLL_STATS;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}POLL_UPDATE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}POLL_UPDATE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}POLLVOTE_CHECK')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}POLLVOTE_CHECK;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}POST_LAST10USER')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}POST_LAST10USER;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}POST_ALLUSER')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}POST_ALLUSER;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}POST_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}POST_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}POST_LIST_REVERSE10')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}POST_LIST_REVERSE10;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}RANK_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}RANK_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}RANK_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}RANK_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}RANK_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}RANK_SAVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}REPLACE_WORDS_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}REPLACE_WORDS_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}REPLACE_WORDS_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}REPLACE_WORDS_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}REPLACE_WORDS_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}REPLACE_WORDS_SAVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}RSSTOPIC_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}RSSTOPIC_LIST;';  END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}SMILEY_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}SMILEY_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}SMILEY_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}SMILEY_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}SMILEY_LISTUNIQUE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}SMILEY_LISTUNIQUE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}SMILEY_RESORT')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}SMILEY_RESORT;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}SMILEY_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}SMILEY_SAVE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}TOPIC_ACTIVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}TOPIC_ACTIVE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}TOPIC_UNREAD')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}TOPIC_UNREAD;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}TOPIC_ANNOUNCEMENTS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}TOPIC_ANNOUNCEMENTS;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}TOPIC_CREATE_BY_MESSAGE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}TOPIC_CREATE_BY_MESSAGE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}TOPIC_FINDNEXT')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}TOPIC_FINDNEXT;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}TOPIC_FINDPREV')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}TOPIC_FINDPREV;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}TOPIC_INFO')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}TOPIC_INFO;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}TOPIC_LISTMESSAGES')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}TOPIC_LISTMESSAGES;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}TOPIC_LOCK')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}TOPIC_LOCK;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}TOPIC_POLL_UPDATE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}TOPIC_POLL_UPDATE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}TOPIC_PRUNE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}TOPIC_PRUNE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}TOPIC_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}TOPIC_SAVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}TOPIC_IMAGESAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}TOPIC_IMAGESAVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}TOPIC_SIMPLELIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}TOPIC_SIMPLELIST;';  END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_ACCESSMASKS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_ACCESSMASKS;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_ACCESSMASKSBYFORUM')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_ACCESSMASKSBYFORUM;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_ACTIVITY_RANK')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_ACTIVITY_RANK;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_ADDIGNOREDUSER')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_ADDIGNOREDUSER;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_ADDPOINTS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_ADDPOINTS;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='USER_REMOVEPOINTS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE USER_REMOVEPOINTS;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_ADMINSAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_ADMINSAVE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_APPROVEALL')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_APPROVEALL;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_ASPNET')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_ASPNET;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_AVATARIMAGE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_AVATARIMAGE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_CHANGEPASSWORD')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_CHANGEPASSWORD;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_DELETEAVATAR')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_DELETEAVATAR;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_DELETEOLD')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_DELETEOLD;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_EMAILS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_EMAILS;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_FIND')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_FIND;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_GET')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_GET;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_GETPOINTS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_GETPOINTS;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_GETSIGNATURE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_GETSIGNATURE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_LISTTODAYSBIRTHDAYS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_LISTTODAYSBIRTHDAYS;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_REMOVEIGNOREDUSER')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_REMOVEIGNOREDUSER;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_ISUSERIGNORED')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_ISUSERIGNORED;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_LASTREAD')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_LASTREAD;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_LIST;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_LIST_OLD')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_LIST_OLD;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_LISTMEDALS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_LISTMEDALS;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_LOGIN')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_LOGIN;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_MEDAL_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_MEDAL_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_MEDAL_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_MEDAL_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_MEDAL_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_MEDAL_SAVE;';  END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_MIGRATE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_MIGRATE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_NNTP')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_NNTP;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_PMCOUNT')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_PMCOUNT;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_RECOVERPASSWORD')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_RECOVERPASSWORD;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_REMOVEPOINTS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_REMOVEPOINTS;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_REMOVEPOINTSBYTOPICID')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_REMOVEPOINTSBYTOPICID;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_RESETPOINTS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_RESETPOINTS;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_SAVEAVATAR')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_SAVEAVATAR;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_SAVEPASSWORD')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_SAVEPASSWORD;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_SAVESIGNATURE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_SAVESIGNATURE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_SETNOTDIRTY')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_SETNOTDIRTY;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_SETPOINTS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_SETPOINTS;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_SETROLE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_SETROLE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_SIMPLELIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_SIMPLELIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_SUSPEND')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_SUSPEND;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_THANKFROMCOUNT')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_THANKFROMCOUNT;';  END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USERREPLIEDTOPIC')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USERREPLIEDTOPIC;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USERFORUM_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USERFORUM_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USERFORUM_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USERFORUM_SAVE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USERGROUP_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USERGROUP_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USERGROUP_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USERGROUP_SAVE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USERPMESSAGE_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USERPMESSAGE_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USERPMESSAGE_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USERPMESSAGE_LIST;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}WATCHFORUM_ADD')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}WATCHFORUM_ADD;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}WATCHFORUM_CHECK')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}WATCHFORUM_CHECK;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}WATCHFORUM_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}WATCHFORUM_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}WATCHTOPIC_ADD')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}WATCHTOPIC_ADD;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}WATCHTOPIC_CHECK')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}WATCHTOPIC_CHECK;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}WATCHTOPIC_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}WATCHTOPIC_LIST;';  END
--GO


--Dependencies

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}ACTIVE_UPDATEMAXSTATS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}ACTIVE_UPDATEMAXSTATS;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}FORUM_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}FORUM_DELETE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}FORUM_MOVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}FORUM_MOVE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}MESSAGE_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}MESSAGE_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}TOPIC_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}TOPIC_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}NNTPFORUM_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}NNTPFORUM_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USERFORUM_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USERFORUM_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USERFORUM_ACCESS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USERFORUM_ACCESS;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}WATCHFORUM_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}WATCHFORUM_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}WATCHTOPIC_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}WATCHTOPIC_DELETE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}TOPIC_UPDATELASTPOST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}TOPIC_UPDATELASTPOST;';  END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}MESSAGE_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}MESSAGE_SAVE;';  END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}VACCESS_UL')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}VACCESS_UL;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}VACCESS_ULF')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}VACCESS_ULF;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_IGNOREDLIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_IGNOREDLIST;';  
END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}SHOUTBOX_GETMESSAGES')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}SHOUTBOX_GETMESSAGES;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}SHOUTBOX_SAVEMESSAGE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}SHOUTBOX_SAVEMESSAGE;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}SHOUTBOX_CLEARMESSAGES')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}SHOUTBOX_CLEARMESSAGES;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}DB_SIZE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}DB_SIZE';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}MESSAGE_ADDTHANKS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}MESSAGE_ADDTHANKS';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}MESSAGE_GETTHANKS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}MESSAGE_GETTHANKS';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}MESSAGE_ISTHANKEDBYUSER')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}MESSAGE_ISTHANKEDBYUSER';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}MESSAGE_MESSAGE_GETALLTHANKS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}MESSAGE_GETALLTHANKS';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}MESSAGE_REMOVETHANKS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}MESSAGE_REMOVETHANKS';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}MESSAGE_REMOVETHANKS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}MESSAGE_REMOVETHANKS';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}MESSAGE_THANKSNUMBER')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}MESSAGE_THANKSNUMBER';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_GETTHANKS_FROM')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_GETTHANKS_FROM';
END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_GETTHANKS_TO')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_GETTHANKS_TO';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}MESSAGE_GETALLTHANKS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}MESSAGE_GETALLTHANKS';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}BUDDY_ADDREQUEST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}BUDDY_ADDREQUEST';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}BUDDY_APPROVEREQUEST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}BUDDY_APPROVEREQUEST';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}BUDDY_DENYREQUEST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}BUDDY_DENYREQUEST';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}BUDDY_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}BUDDY_LIST';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}BUDDY_REMOVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}BUDDY_REMOVE';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}TOPIC_FAVORITE_ADD')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}TOPIC_FAVORITE_ADD';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}TOPIC_FAVORITE_REMOVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}TOPIC_FAVORITE_REMOVE';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}TOPIC_FAVORITE_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}TOPIC_FAVORITE_LIST';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}TOPIC_FAVORITE_DETAILS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}TOPIC_FAVORITE_DETAILS';
END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}ALBUM_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}ALBUM_SAVE';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}ALBUM_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}ALBUM_LIST';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}ALBUM_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}ALBUM_DELETE';
END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}ALBUM_GETTITLE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}ALBUM_GETTITLE';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}ALBUM_GETSTATS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}ALBUM_GETSTATS';
END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}ALBUM_IMAGE_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}ALBUM_IMAGE_SAVE';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}ALBUM_IMAGE_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}ALBUM_IMAGE_LIST';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}ALBUM_IMAGES_BYUSER')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}ALBUM_IMAGES_BYUSER';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}ALBUM_IMAGE_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}ALBUM_IMAGE_DELETE';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}ALBUM_IMAGE_DOWNLOAD')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}ALBUM_IMAGE_DOWNLOAD';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_GETSIGNATUREDATA')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_GETSIGNATUREDATA';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_GETALBUMSDATA')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_GETALBUMSDATA';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}MESSAGE_SECDATA')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}MESSAGE_SECDATA';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}MESSAGEHISTORY_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}MESSAGEHISTORY_LIST';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}ACTIVE_LIST_USER')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}ACTIVE_LIST_USER';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_VIEWALLTHANKS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_VIEWALLTHANKS';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 W
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_VIEWTHANKSTO')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_VIEWTHANKSTO';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 W
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_VIEWTHANKSFROM')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_VIEWTHANKSFROM';
END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_LAZYDATA')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_LAZYDATA';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_LISTMEMBERS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_LISTMEMBERS';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}MESSAGE_GETTEXTBYIDS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}MESSAGE_GETTEXTBYIDS';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}BOARD_USERSTATS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}BOARD_USERSTATS';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}RSS_TOPIC_LATEST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}RSS_TOPIC_LATEST';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}TOPIC_FINDDUPLICATE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}TOPIC_FINDDUPLICATE';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}POLLGROUP_STATS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}POLLGROUP_STATS';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}POLLGROUP_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}POLLGROUP_LIST';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}POLLGROUP_ATTACH')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}POLLGROUP_ATTACH';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}POLLGROUP_VOTECHECK')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}POLLGROUP_VOTECHECK';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}POLLGROUP_REMOVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}POLLGROUP_REMOVE';
END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}TOPIC_FAVORITE_COUNT')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}TOPIC_FAVORITE_COUNT';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}TOPICS_BYUSER')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}TOPICS_BYUSER';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}READTOPIC_ADDORUPDATE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}READTOPIC_ADDORUPDATE';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}READTOPIC_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}READTOPIC_DELETE';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}READTOPIC_LASTREAD')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}READTOPIC_LASTREAD';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}READFORUM_ADDORUPDATE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}READFORUM_ADDORUPDATE';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}READFORUM_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}READFORUM_DELETE';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}READFORUM_LASTREAD')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}READFORUM_LASTREAD';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}RECENT_USERS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}RECENT_USERS';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_THANKEDMESSAGE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_THANKEDMESSAGE';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}ACTIVEACCESS_RESET')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}ACTIVEACCESS_RESET';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}BOARD_SETGUIG')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}BOARD_SETGUIG';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}ADMIN_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}ADMIN_LIST';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_LISTMEMBERS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_LISTMEMBERS';
END
--GO



EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}TOPICSTATUS_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}TOPICSTATUS_DELETE';
END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}TOPICSTATUS_EDIT')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}TOPICSTATUS_EDIT';
END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}TOPICSTATUS_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}TOPICSTATUS_LIST';
END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}TOPICSTATUS_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}TOPICSTATUS_SAVE';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_UPDATEFACEBOOKSTATUS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_UPDATEFACEBOOKSTATUS';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}DBINFO_TABLE_COLUMNS_INFO')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}DBINFO_TABLE_COLUMNS_INFO';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}ALBUM_IMAGES_BY_USER')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}ALBUM_IMAGES_BY_USER';
END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}ADMINPAGEACCESS_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}ADMINPAGEACCESS_SAVE';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}ADMINPAGEACCESS_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}ADMINPAGEACCESS_DELETE';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}ADMINPAGEACCESS_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}ADMINPAGEACCESS_LIST';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}ADMIN_PAGEACCESSLIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}ADMIN_PAGEACCESSLIST';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}EVENTLOGGROUPACCESS_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}EVENTLOGGROUPACCESS_SAVE';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}EVENTLOGGROUPACCESS_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}EVENTLOGGROUPACCESS_DELETE';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}EVENTLOGGROUPACCESS_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}EVENTLOGGROUPACCESS_LIST';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}EVENTLOG_DELETEBYUSER')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}EVENTLOG_DELETEBYUSER';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}GROUP_EVENTLOGACCESSLIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}GROUP_EVENTLOGACCESSLIST';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}FORUM_CATACCESS_ACTIVEUSER')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}FORUM_CATACCESS_ACTIVEUSER';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}MESSAGE_APPROVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}MESSAGE_APPROVE;';  END
--GO



EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_APPROVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_APPROVE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}TOPIC_MOVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}TOPIC_MOVE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}TOPIC_RESTORE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}TOPIC_RESTORE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}FORUM_RESYNC')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}FORUM_RESYNC;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}FORUM_UPDATELASTPOST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}FORUM_UPDATELASTPOST;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}BOARD_CREATE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}BOARD_CREATE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}REGISTRY_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}REGISTRY_SAVE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_SAVESTYLE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_SAVESTYLE;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_UPGRADE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_UPGRADE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}FORUM_UPDATESTATS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}FORUM_UPDATESTATS;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}POLLGROUP_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}POLLGROUP_SAVE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}POLLGROUP_SETLINKS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}POLLGROUP_SETLINKS;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}POLL_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}POLL_SAVE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}CHOICE_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}CHOICE_SAVE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USERPROFILE_SETPROPERTIES')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USERPROFILE_SETPROPERTIES;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}SEARCH_SIMPLE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}SEARCH_SIMPLE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}FORUM_NS_RECREATE_INI')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}FORUM_NS_RECREATE_INI';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}FORUM_NS_RECREATE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}FORUM_NS_RECREATE';
END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}CR_OR_CHCK_NS_TABLES')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}CR_OR_CHCK_NS_TABLES';
END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}FILLIN_OR_CHECK_NS_TABLE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}FILLIN_OR_CHECK_NS_TABLE';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME=UPPER('{objectQualifier}forum_ns_before_insert_func'))) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}forum_ns_before_insert_func';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME=UPPER('{objectQualifier}FORUM_BEFORE_INSERT_FUNC'))) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}FORUM_BEFORE_INSERT_FUNC';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME=UPPER('{objectQualifier}forum_ns_after_del2_func'))) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}forum_ns_after_del2_func';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME=UPPER('{objectQualifier}FORUM_AFTER_DEL2_FUNC'))) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}FORUM_AFTER_DEL2_FUNC';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME=UPPER('{objectQualifier}FORUM_AFTER_DEL_FUNC'))) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}FORUM_AFTER_DEL_FUNC';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME=UPPER('{objectQualifier}forum_ns_after_delete_func'))) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}forum_ns_after_delete_func';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME=UPPER('{objectQualifier}FORUM_BEFORE_UPDATE_FUNC'))) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}FORUM_BEFORE_UPDATE_FUNC';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME=UPPER('{objectQualifier}forum_ns_dropbridge_triggers'))) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}forum_ns_dropbridge_triggers';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME=UPPER('{objectQualifier}forum_ns_drop_triggers'))) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}forum_ns_drop_triggers';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME=UPPER('{objectQualifier}LOCK_NS_TREE'))) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}LOCK_NS_TREE';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME=UPPER('{objectQualifier}forum_ns_after_delete_2_func'))) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}forum_ns_after_delete_2_func';
END
--GO



EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME=UPPER('{objectQualifier}forum_ns_before_update_func'))) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}forum_ns_before_update_func';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME=UPPER('{objectQualifier}forum_ns_create_triggers'))) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}forum_ns_create_triggers';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME=UPPER('{objectQualifier}forum_ns_forumsavegetparent'))) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}forum_ns_forumsavegetparent';
END
--GO



EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME=UPPER('{objectQualifier}FORUM_NS_GETCH_ACCGROUP'))) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}FORUM_NS_GETCH_ACCGROUP';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME=UPPER('{objectQualifier}forum_ns_getchildren'))) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}forum_ns_getchildren';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME=UPPER('{objectQualifier}forum_ns_getch_actuser'))) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}forum_ns_getch_actuser';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME=UPPER('{objectQualifier}forum_ns_getch_anyuser'))) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}forum_ns_getch_anyuser';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME=UPPER('{objectQualifier}forum_ns_getpath'))) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}forum_ns_getpath';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME=UPPER('{objectQualifier}forum_ns_listpath'))) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}forum_ns_listpath';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='{objectQualifier}USER_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE {objectQualifier}USER_SAVE;';  END
--GO




