/* Yet Another Forum.NET Firebird data layer by vzrus
 * Copyright (C) 2006-2016 Vladimir Zakharov
 * https://github.com/vzrus
 * http://sourceforge.net/projects/yaf-datalayers/
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; version 2 only
 * General class structure is based on MS SQL Server code,
 * created by YAF developers
 *
 * http://www.yetanotherforum.net/
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation;version 2 only
 * of the License.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

EXECUTE BLOCK
AS
BEGIN
	 IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
					 WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}ACCESSMASK_ACCESSMASKID' 
					   AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
		 EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}ACCESSMASK_ACCESSMASKID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
	 IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
					 WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}ATTACHMENT_ATTACHMENTID' 
					   AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
		 EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}ATTACHMENT_ATTACHMENTID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
	 IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
					 WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}BANNEDIP_ID' 
					   AND a.RDB$SYSTEM_FLAG =0  ROWS 1)) THEN
		 EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}BANNEDIP_ID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
	 IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
					 WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}BBCODE_BBCODEID' 
					   AND a.RDB$SYSTEM_FLAG =0  ROWS 1)) THEN
		 EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}BBCODE_BBCODEID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
	 IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
					 WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}BOARD_BOARDID' 
					   AND a.RDB$SYSTEM_FLAG =0  ROWS 1)) THEN
		 EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}BOARD_BOARDID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
				WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}CATEGORY_CATEGORYID' 
				  AND a.RDB$SYSTEM_FLAG =0  ROWS 1)) THEN
	EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}CATEGORY_CATEGORYID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
	 IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
					 WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}CHECKEMAIL_CHECKEMAILID' 
					   AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
		 EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}CHECKEMAIL_CHECKEMAILID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
	 IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
					 WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}CHOICE_CHOICEID' 
					 AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
		 EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}CHOICE_CHOICEID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
	 IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
					 WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}EVENTLOG_EVENTLOGID' 
					   AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
		 EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}EVENTLOG_EVENTLOGID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
	 IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
					 WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}EXTENSION_EXTENSIONID' 
					   AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
		 EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}EXTENSION_EXTENSIONID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
	 IF (NOT EXISTS (SELECT 1
					 FROM RDB$GENERATORS a
					 WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}FORUM_FORUMID' 
					   AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
		 EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}FORUM_FORUMID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
	 IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
					 WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}GROUP_GROUPID' 
					   AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
		 EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}GROUP_GROUPID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
	 IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
					 WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}MAIL_MAILID' 
					   AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
		 EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}MAIL_MAILID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
				WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}MEDAL_MEDALID' 
				  AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
   EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}MEDAL_MEDALID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
	 IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
					 WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}MESSAGE_MESSAGEID' 
					   AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
		 EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}MESSAGE_MESSAGEID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
	 IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
					 WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}MESSAGE_LOGID' 
					   AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
		 EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}MESSAGE_LOGID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
	 IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
					 WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}NNTPFORUM_NNTPFORUMID' 
					   AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
		 EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}NNTPFORUM_NNTPFORUMID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
	 IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
					 WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}NNTPSERVER_NNTPSERVERID' 
					   AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
		EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}NNTPSERVER_NNTPSERVERID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
	 IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
					 WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}NNTPTOPIC_NNTPTOPICID' 
					   AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
		 EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}NNTPTOPIC_NNTPTOPICID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
	 IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
					 WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}PMESSAGE_PMESSAGEID' 
					   AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
		EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}PMESSAGE_PMESSAGEID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
	 IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
					 WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}POLL_POLLID' 
					   AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
		 EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}POLL_POLLID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
	 IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
					 WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}POLLVOTE_POLLVOTEID' 
					   AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
		 EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}POLLVOTE_POLLVOTEID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
	 IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
					 WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}RANK_RANKID' 
					   AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
		 EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}RANK_RANKID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
	 IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
					 WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}REGISTRY_REGISTRYID' 
					   AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
		 EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}REGISTRY_REGISTRYID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
	 IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
					 WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}REPLACE_WORDS_ID' 
					   AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
		 EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}REPLACE_WORDS_ID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
	 IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
					 WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}SMILEY_SMILEYID' 
					   AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
		 EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}SMILEY_SMILEYID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
	 IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
					 WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}TOPIC_TOPICID' 
					   AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
		 EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}TOPIC_TOPICID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
	 IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
					 WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}USER_USERID' 
					   AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
		 EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}USER_USERID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
	 IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
					 WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}USERPME_USERPMESSAGEID' 
					   AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
		 EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}USERPME_USERPMESSAGEID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
	 IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
					 WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}WATCHFORUM_WATCHFORUMID' 
					   AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
		 EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}WATCHFORUM_WATCHFORUMID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
				WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}WATCHTOPIC_WATCHTOPICID' 
				  AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
	EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}WATCHTOPIC_WATCHTOPICID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
				WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}SBOXMESG_SBOXMESGID' 
				  AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
	EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}SBOXMESG_SBOXMESGID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
				WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}THANKS_THANKSID' 
				  AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
	EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}THANKS_THANKSID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
				WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}BUDDY_ID' 
				  AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
	EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}BUDDY_ID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
				WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}FAVORITETOPIC_ID' 
				  AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
	EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}FAVORITETOPIC_ID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
	 IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
					 WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}USERALBUM_ALBUMID' 
					   AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
		 EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}USERALBUM_ALBUMID;';
END
--GO


EXECUTE BLOCK
AS
BEGIN
	 IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
					 WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}USRALBIMG_IMAGEID' 
					   AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
		 EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}USRALBIMG_IMAGEID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
	 IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
					 WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}MSGHIS_MSGHISID' 
					 AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
		 EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}MSGHIS_MSGHISID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
	 IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
					 WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}PGC_POLLGROUPID' 
					   AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
		 EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}PGC_POLLGROUPID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
	 IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
					 WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}TOPSTATUS_TOPSTID' 
					   AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
		 EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}TOPSTATUS_TOPSTID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
	 IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
					 WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}TAGS_TAGID' 
					   AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
		 EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}TAGS_TAGID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
	 IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
					 WHERE a.RDB$GENERATOR_NAME='SEQ_{objectQualifier}FORUM_NS_NID' 
					   AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
		 EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_{objectQualifier}FORUM_NS_NID;';
END
--GO




